### ISSUE TITLE
Use a python code formatter 

### ISSUE THREAD

**Issue by pnijhara** [PacktPublishing/Machine-Learning-Automation-with-TPOT#1]
Repo should go under a code formatter to stay consistent in code quality. I recommend black.

**Comment by sonam-packt** [comment]
Hi @pnijhara
Since the book is still under production, these are not the final codes. There may be changes and updates to the code depending on the testing done by the technical editor. We'll make sure to check on this issue and resolve it while testing.

Thanks for the heads-up!

**Comment by pnijhara** [comment]
@sonam-packt I have opened these issues as reminders and I am the one who did the testing of the code along with technical reviewing.
