### ISSUE TITLE
Remove empty spaces

### ISSUE THREAD

**Issue by pnijhara** [PacktPublishing/Machine-Learning-Automation-with-TPOT#2]
Files:
1. Chapter5/001_basic_parallelism/002.py
2. Chapter5/001_basic_parallelism/003.py
3. Chapter5/001_basic_parallelism/004.py
4. Chapter5/001_basic_parallelism/005.py
5. Chapter8/api/app.py
6. Chapter8/flask_basics.py

contains empty spaces, which can be removed.

**Comment by sonam-packt** [comment]
Hi @pnijhara
Since the book is still under production, these are not the final files. There may be changes and updates to the code depending on the testing done by the technical editor. We'll make sure to check on this issue and resolve it while testing.

Thanks for the heads-up!
