### ISSUE TITLE
Leave a line after end of the file.

### ISSUE THREAD

**Issue by pnijhara** [PacktPublishing/Machine-Learning-Automation-with-TPOT#3]
Leave an empty line after the following files.
1. Chapter8/api/app.py
2. Chapter8/api/helpers.py
3. Chapter8/flask_basics2.py
4. Chapter8/flask_python_request.py
5. Chapter9/webapp/app.py
6. Chapter9/webapp/forms.py

**Comment by ManikandanKurup-Packt** [comment]
Hi @pnijhara 
Thanks for your feedback. We'll make sure to incorporate it.
