### ISSUE TITLE
Unnecessary else / elif used after return

### ISSUE THREAD

**Issue by pnijhara** [PacktPublishing/Machine-Learning-Automation-with-TPOT#4]
## Description
`return` statement causes the control flow to be disrupted, making the `else` / `elif` block here unnecessary. This doesn&#x27;t mean you can not use it, but it is recommended to refactor this for a better readability. Bad: ```python def classify_number(x): if x % 2 == 0: return &#x27;Even&#x27; else: return …

## Occurrences
There is 1 occurrence of this issue in the repository.
https://github.com/PacktPublishing/Machine-Learning-Automation-with-TPOT/blob/main/Chapter8/api/helpers.py#L1-L9

**Comment by pnijhara** [comment]
Possible solution:
```python
def int_to_species(in_species):
    if in_species == 0:
        return 'setosa'
    if in_species == 1:
        return 'virginica'
    if in_species == 2:
        return 'versicolor'
    else:
        return ''
```

I have some concerns with the empty return after else. This should also be removed. What do you say @daradecic

**Comment by ManikandanKurup-Packt** [comment]
Hi @pnijhara 
Since the book is still under production, these are not the final codes. There may be changes and updates to the code depending on the testing done by the technical editor. We'll make sure to check on this issue and resolve it while testing. 

Thanks for the heads-up!
